# -*- coding: utf-8 -*-
"""test_ragas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNcVaZ9qSjpTWN6-9Ix3ewanPXLXlcAo
"""

# Ragas 및 HuggingFace 오픈소스 연동을 위한 필수 라이브러리 설치
!pip install -qU ragas langchain-huggingface transformers accelerate bitsandbytes sentence-transformers nest-asyncio

import nest_asyncio
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline, BitsAndBytesConfig
from langchain_huggingface import HuggingFacePipeline, HuggingFaceEmbeddings

from datasets import Dataset
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy

nest_asyncio.apply()

print("⏳ 1. 오픈소스 임베딩 모델 로딩 중...")
embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-m3")

print("⏳ 2. 오픈소스 LLM (평가관) 4비트 양자화 로딩 중...")
model_id = "Qwen/Qwen2.5-7B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

# ✅ 수정된 부분: BitsAndBytesConfig 객체 생성
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

# 코랩 T4 GPU 메모리에 맞추기 위해 4bit 로드 (quantization_config 사용)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    quantization_config=bnb_config
)

# LangChain 연동을 위한 파이프라인 구축
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    temperature=0.1
)

llm = HuggingFacePipeline(pipeline=pipe)
print("✅ 모델 로딩 완료!")

print("⏳ 3. Ragas 평가 테스트 시작...")

# 테스트용 데이터셋 구성 (사용자 질문, RAG의 답변, 참조한 원본 문맥, 모범 답안)
data = {
    "question": [
        "최근 arXiv에 올라온 RAG 관련 논문들에서 주로 다루는 검색 최적화 기법은 무엇인가요?"
    ],
    "answer": [
        "최근 arXiv 동향을 보면, 벡터 검색의 한계를 보완하기 위해 키워드 검색을 결합하는 하이브리드 검색과 Re-ranking 모델을 도입하는 기법이 주를 이루고 있습니다."
    ],
    "contexts": [
        ["최근 1개월간 arXiv에 등록된 AI 트렌드 리포트에 따르면, 단순 벡터 검색(Dense Retrieval)만으로는 고유 명사 처리에 한계가 있어 BM25 등 스파스 검색을 결합한 하이브리드 검색이 표준화되고 있다. 또한 Cross-Encoder를 활용한 Re-ranking 파이프라인이 필수적으로 요구된다."]
    ],
    "ground_truth": [
        "하이브리드 검색(키워드+벡터)과 Re-ranking 모델의 도입입니다."
    ]
}

dataset = Dataset.from_dict(data)

# Ragas 평가 실행 (오픈소스 LLM과 임베딩 모델 주입)
result = evaluate(
    dataset=dataset,
    metrics=[
        faithfulness,      # 문맥과 답변이 사실적으로 일치하는가?
        answer_relevancy   # 질문에 대해 엉뚱한 소리를 하지 않았는가?
    ],
    llm=llm,
    embeddings=embeddings,
    raise_exceptions=False # 오픈소스 LLM의 파싱 에러로 인한 전체 중단 방지
)

print("\n✅ [최종 평가 결과]")
print(result)

