services:
  vllm:
    build:
      context: .
      dockerfile: Dockerfile.vllm
    ports:
      - 8000:8000
    environment:
      - MODEL_NAME=EXAONE-3.5-2.4B-Instruct-Q4_K_M.gguf
    volumes:
      - ./llm_models:/root/.cache/huggingface
    command: vllm serve ${MODEL_NAME} --host 0.0.0.0 --port 8000